


#include <iostream>
#include <string>
using namespace std;


//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.



class Solution {
public:
    // 方法1：差值法，俩字符串的ascii数值和的差就是多出来的字符的ascii码值
    char findTheDifference(string s, string t) {
        int sum = 0;
        int i;
        for(i=0; i<s.length(); i++){
            sum = t[i] - s[i];
        }
        sum += t[i]; // 最后一位
        return char(sum);
    }
    // 方法2：抑或法，俩相同值异或为0
    char findTheDifference2(string s, string t) {
        int res = 0;
        int i;
        for(i=0; i<s.length(); i++){
            res ^= s[i];
            res ^= t[i];
        }
        res ^= t[i]; // 最后一位
        return res;
    }
};

int main(int argc, const char * argv[]) {
    string str = "abcddd";
    string t = "abcgddd";
    Solution s;
    
    cout << s.findTheDifference2(str, t) << endl;
    return 0;
}


